# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'StarWars' do
  pod "SwiftyJSON"
  pod "Alamofire"
  pod "PromiseKit"
end

target 'StarWarsTests' do

end

